language: objective-c
osx_image: xcode9
before_install:
  - brew install llvm
  - export PATH=$PATH:/usr/local/opt/llvm/bin
install:
  - sudo swift utils/make-pkgconfig.swift
script: swift build -c release && swift test
